version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    volumes:
      - /var/local/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
